# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - blogpost-interactive-elements

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure_functions'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # No pip install step here! Let Azure do the build.

      - name: Verify Azure Functions structure
        run: |
          echo "=== Checking Azure Functions directory structure ==="
          ls -R azure_functions/
          echo "=== Verifying function.json files ==="
          find azure_functions -name "function.json" -type f -exec echo {} \;
          echo "=== Checking for __init__.py files ==="
          find azure_functions -name "__init__.py" -type f -exec echo {} \;

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09790B90DBD44A609A797839C08828C6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9AFF6D2750544912AEC0CF82767B7EBD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9326CBE749D846C9A0532C3190718D4F }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'blogpost-interactive-elements'
          slot-name: 'Production'
          package: ./azure_functions
          